import React, { useEffect, useState } from 'react';
import { onAuthStateChanged, type User } from 'firebase/auth';
import { auth } from '../lib/firebase';
import { apiRequest, backendSession } from '../lib/api';

type AdminData = { users: { uid: string; email: string; displayName: string; role: string }[]; calls: { id: string; status: string; mode: string }[]; inquiries: { id: string; status?: string; contactName?: string; email?: string }[] };
export const AdminDashboardPage: React.FC = () => {
  const [user, setUser] = useState<User | null>(null); const [data, setData] = useState<AdminData | null>(null); const [error, setError] = useState('');
  const refresh = async () => setData(await apiRequest<AdminData>('/v1/dashboard/admin'));
  useEffect(() => { if (!auth) return; return onAuthStateChanged(auth, async (current) => { setUser(current); if (!current) return; try { await backendSession(current); await refresh(); } catch (e) { setError(e instanceof Error ? e.message : 'Could not load admin dashboard.'); } }); }, []);
  const setRole = async (uid: string, role: string) => { try { await apiRequest(`/v1/admin/users/${encodeURIComponent(uid)}/role`, { method: 'PATCH', body: JSON.stringify({ role }) }); await refresh(); } catch (e) { setError(e instanceof Error ? e.message : 'Could not update role.'); } };
  return <main className="min-h-screen bg-[#0B0D0C] px-4 pb-20 pt-36 text-[#DEDBD2]"><div className="mx-auto max-w-6xl"><h1 className="text-3xl font-bold text-white">Lumera Admin</h1>{!user && <p className="mt-4 text-sm text-[#A8A498]">Sign in with the administrator account.</p>}{error && <p role="alert" className="mt-4 text-sm text-red-300">{error}</p>}{data && <><section className="mt-8 rounded-2xl border border-[#252D27] bg-[#111412] p-6"><h2 className="text-xl font-semibold text-white">Accounts and roles</h2>{data.users.map((account) => <div key={account.uid} className="flex flex-wrap items-center justify-between gap-3 border-b border-[#252D27] py-3 text-sm"><span>{account.displayName || account.email || account.uid}</span><select value={account.role} onChange={(e) => void setRole(account.uid, e.target.value)} className="rounded border border-[#303831] bg-[#0B0D0C] p-2"><option value="customer">Customer</option><option value="agent">Agent</option><option value="admin">Admin</option></select></div>)}</section><section className="mt-6 grid gap-6 md:grid-cols-2"><div className="rounded-2xl border border-[#252D27] bg-[#111412] p-6"><h2 className="text-xl font-semibold text-white">Calls ({data.calls.length})</h2>{data.calls.map((call) => <p key={call.id} className="mt-3 text-sm">{call.mode} · {call.status}</p>)}</div><div className="rounded-2xl border border-[#252D27] bg-[#111412] p-6"><h2 className="text-xl font-semibold text-white">Inquiries ({data.inquiries.length})</h2>{data.inquiries.map((inquiry) => <p key={inquiry.id} className="mt-3 text-sm">{inquiry.contactName} · {inquiry.email} · {inquiry.status || 'new'}</p>)}</div></section></>}</div></main>;
};
